CREATE SCHEMA LIBRARY;
USE LIBRARY;

CREATE TABLE PUBLISHER(
	`name` VARCHAR(30),
    address VARCHAR(30) NOT NULL,
    phone VARCHAR(12) NOT NULL UNIQUE,
    CONSTRAINT PUBPK 
		PRIMARY KEY(`name`)
);

CREATE TABLE `USER`(
	id INT AUTO_INCREMENT,
    firstName VARCHAR(20) NOT NULL,
    lastName VARCHAR(20) NOT NULL,
    email VARCHAR(30) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    manager BIT(1) DEFAULT 0,
    CONSTRAINT USERPK 
		PRIMARY KEY(id)
);

CREATE TABLE BOOK(
	ISBN INT,
    title VARCHAR(100) NOT NULL UNIQUE,
    publisherName VARCHAR(30) NOT NULL,
    authors VARCHAR(500) NOT NULL,
    publicationYear CHAR(4),
    coverImage VARCHAR(7000),
    price FLOAT NOT NULL,
    CONSTRAINT PRICE_RANGE CHECK (PRICE >= 0),
    category ENUM('Science','Art','Religion','History','Geography') NOT NULL,
	threshold INT NOT NULL,
    stockQuantity INT NOT NULL,
	CONSTRAINT THRESHOLD_RANGE CHECK (threshold >= 0),
    CONSTRAINT STOCK_QUANTITY_RANGE CHECK (stockQuantity >= 0),
    CONSTRAINT BPK
		PRIMARY KEY(ISBN),
	CONSTRAINT PUBFK
		FOREIGN KEY(publisherName) REFERENCES PUBLISHER(`name`)
			ON UPDATE CASCADE ON DELETE RESTRICT 
);

CREATE TABLE STOCK_ORDER(
	id INT NOT NULL AUTO_INCREMENT,
	ISBN INT NOT NULL,
	quantity INT NULL,
    CONSTRAINT ORDERPK
		PRIMARY KEY(id),
	CONSTRAINT ORDER_BOOK_FK
		FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN)
			ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE CUSTOMER_ORDER(
	id INT AUTO_INCREMENT,
    userId INT NOT NULL,
    `date` DATE NOT NULL,
    CONSTRAINT CARTPK
		PRIMARY KEY(id),
	CONSTRAINT CUSTOMER_ORDER_USER_FK
		FOREIGN KEY(userId) REFERENCES USER(id)
);

CREATE TABLE CUSTOMER_ORDER_ITEM(
	ISBN INT NOT NULL,
    copies INT NOT NULL,
	customerOrderId INT NOT NULL,
    CONSTRAINT ITEMPK
		PRIMARY KEY(ISBN, customerOrderId),
	CONSTRAINT ITEM_BOOK_FK
		FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN)
			ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT CUSTOMER_ORDER_FK
		FOREIGN KEY(customerOrderId) REFERENCES CUSTOMER_ORDER(id)
			ON UPDATE RESTRICT ON DELETE CASCADE
);

#-----creating index on category attribute in BOOK table

ALTER TABLE BOOK ADD INDEX categoryIndex(category);


#----------Triggers----------------

delimiter //
CREATE TRIGGER `book_BEFORE_UPDATE` BEFORE UPDATE ON `book`
 FOR EACH ROW BEGIN
	IF NEW.stockQuantity < 0 THEN
	  SIGNAL SQLSTATE '45000' SET 
      MESSAGE_TEXT = 'Stock quantity of book can not be negative!';
    END IF;
END //

delimiter //
CREATE TRIGGER `book_AFTER_UPDATE` AFTER UPDATE ON `book` FOR EACH ROW BEGIN
	IF NEW.stockQuantity < NEW.threshold AND NOT EXISTS (SELECT * FROM STOCK_ORDER AS S WHERE S.ISBN = NEW.ISBN) THEN
		CALL place_order(NEW.ISBN, NEW.threshold - NEW.stockQuantity + 0.6 * NEW.threshold);
	END IF;
END //


delimiter //
CREATE TRIGGER `stock_order_BEFORE_DELETE` BEFORE DELETE ON `stock_order` FOR EACH ROW BEGIN
	UPDATE BOOK AS B
    SET B.stockQuantity = B.stockQuantity + OLD.quantity
    WHERE B.ISBN = OLD.ISBN;
END //

#-----Stored procedure------

DELIMITER $$
USE `library`$$
CREATE PROCEDURE `place_order` (isbn INT, quan INT)
BEGIN
	INSERT INTO STOCK_ORDER (ISBN, quantity) VALUE(isbn, quan);
END$$
