CREATE DEFINER=`root`@`localhost` TRIGGER `book_AFTER_UPDATE` AFTER UPDATE ON `book` FOR EACH ROW BEGIN
	DECLARE message VARCHAR(150);
	IF NEW.stockQuantity < NEW.threshold THEN
		SET message = CONCAT('WARNING! PLEASE PLACE AN ORDER FOR ', NEW.title);
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = message;
	END IF;
END